[tox]
envlist = py39, py310, py311, py312
isolated_build = true

[testenv]
extras = dev
commands =
    pytest {posargs}

[testenv:lint]
extras = dev
commands =
    black --check src tests
    isort --check-only src tests
    flake8 src tests
    mypy src

[testenv:format]
extras = dev
commands =
    black src tests
    isort src tests
